src/Entity/Product.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


#[ORM\Entity(repositoryClass: "App\Repository\ProductRepository")]
#[ORM\Table(name: "mia_product")]
#[UniqueEntity(fields: ['sale_point', 'cod'], message: "Ya se encuentra registrado este código")]
class Product
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "bigint")]
    protected $id;

    #[ORM\Column(name: "name", type: "string", nullable: false, length: 255)]
    protected $name;

    #[ORM\Column(name: "slug", type: "string", nullable: false, length: 255)]
    protected $slug;

    #[ORM\Column(name: "description", type: "text", nullable: true)]
    protected $description;

    #[ORM\Column(name: "created_at", type: "datetime", nullable: false)]
    protected $created_at;

    #[ORM\Column(type: "string", length: 100, nullable: "true")]
    private $cod;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: "products")]
    private $category;

    #[ORM\ManyToOne(targetEntity: Brand::class, inversedBy: "products")]
    private $brand;

    #[ORM\Column(type: "boolean", nullable: true, options: ["default" => False])]
    private $visible;

    #[ORM\OneToMany(targetEntity: ProductImages::class, mappedBy: "product", orphanRemoval: true)]
    private $image;

    #[ORM\ManyToOne(targetEntity: Subcategory::class, inversedBy: "products")]
    private $subcategory;

    #[ORM\Column(type: "text", nullable: true)]
    private $long_description;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $sale_point = null;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductsSalesPoints::class)]
    private Collection $productsSalesPoints;

    #[ORM\ManyToOne(inversedBy: 'product')]
    private ?Color $color = null;

    #[ORM\ManyToOne(inversedBy: 'product')]
    private ?Model $model = null;

    #[ORM\ManyToOne(inversedBy: 'product')]
    private ?ScreenSize $screenSize = null;

    #[ORM\ManyToOne(inversedBy: 'product')]
    private ?ScreenResolution $screenResolution = null;

    #[ORM\ManyToOne(inversedBy: 'product')]
    private ?CPU $CPU = null;

    #[ORM\ManyToOne(inversedBy: 'product')]
    private ?GPU $GPU = null;

    #[ORM\ManyToOne(inversedBy: 'product')]
    private ?Memory $memory = null;

    #[ORM\ManyToOne(inversedBy: 'product')]
    private ?Storage $storage = null;

    #[ORM\ManyToOne(inversedBy: 'product')]
    private ?OS $OS = null;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: StockProduct::class)]
    private Collection $stockProducts;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductAdminInventory::class)]
    private Collection $productAdminInventories;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductDispatch::class)]
    private Collection $productDispatches;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->visible = false;
        $this->image = new ArrayCollection();
        $this->shoppingCarts = new ArrayCollection();
        $this->productsSalesPoints = new ArrayCollection();
        $this->stockProducts = new ArrayCollection();
        $this->productAdminInventories = new ArrayCollection();
        $this->productDispatches = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string|null $name
     * @return $this
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        $slugify = new Slugify();

        $this->slug = $slugify->slugify($name);

        return $this;
    }

    /**
     * @return string
     */
    public function getSlug(): string
    {
        return $this->slug;
    }

    /**
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string|null $description
     * @return $this
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }


    /**
     * @return \DateTime
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    /**
     * @param \DateTime $created_at
     * @return $this
     */
    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }


    public function getCod(): ?string
    {
        return strtoupper($this->cod);
    }

    public function setCod(?string $cod): self
    {
        $this->cod = strtoupper($cod);

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getBrand(): ?Brand
    {
        return $this->brand;
    }

    public function setBrand(?Brand $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(?bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }


    /**
     * @return Collection<int, ProductImages>
     */
    public function getImage(): Collection
    {
        return $this->image;
    }

    public function addImage(ProductImages $image): self
    {
        if (!$this->image->contains($image)) {
            $this->image[] = $image;
            $image->setProduct($this);
        }

        return $this;
    }

    public function getPrincipalImage()
    {
        $principalImage = $this->getImage()->filter(function (ProductImages $productImages) {
            return $productImages->getPrincipal();
        });
        return $principalImage->first() ? $principalImage->first()->getImage() : null;
    }

    public function removeImage(ProductImages $image): self
    {
        if ($this->image->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProduct() === $this) {
                $image->setProduct(null);
            }
        }

        return $this;
    }

    public function getSubcategory(): ?Subcategory
    {
        return $this->subcategory;
    }

    public function setSubcategory(?Subcategory $subcategory): self
    {
        $this->subcategory = $subcategory;

        return $this;
    }

    public function getFullDataProduct()
    {
        return [
            'id' => $this->getId(),
            'category_id' => $this->getCategory()->getId(),
            'subcategory_id' => $this->getSubcategory() ? $this->getSubcategory()->getId() : '',
            'brand_id' => $this->getBrand()->getId(),
            'cod' => $this->getCod(),
            'name' => $this->getName(),
            'description' => $this->getDescription(),
        ];
    }

    public function getLongDescription(): ?string
    {
        return $this->long_description;
    }

    public function setLongDescription(?string $long_description): self
    {
        $this->long_description = $long_description;

        return $this;
    }




    public function getBasicDataProduct()
    {
        return [
            "id" => (int)$this->getId(),
            "name" => $this->getName(),
            "image" => $this->getPrincipalImage(),
        ];
    }

    public function getSalePoint(): ?User
    {
        return $this->sale_point;
    }

    public function setSalePoint(?User $sale_point): static
    {
        $this->sale_point = $sale_point;

        return $this;
    }

    /**
     * @return Collection<int, ProductsSalesPoints>
     */
    public function getProductsSalesPoints(): Collection
    {
        return $this->productsSalesPoints;
    }

    public function addProductsSalesPoint(ProductsSalesPoints $productsSalesPoint): static
    {
        if (!$this->productsSalesPoints->contains($productsSalesPoint)) {
            $this->productsSalesPoints->add($productsSalesPoint);
            $productsSalesPoint->setProduct($this);
        }

        return $this;
    }

    public function removeProductsSalesPoint(ProductsSalesPoints $productsSalesPoint): static
    {
        if ($this->productsSalesPoints->removeElement($productsSalesPoint)) {
            // set the owning side to null (unless already changed)
            if ($productsSalesPoint->getProduct() === $this) {
                $productsSalesPoint->setProduct(null);
            }
        }

        return $this;
    }

    public function getColor(): ?Color
    {
        return $this->color;
    }

    public function setColor(?Color $color): static
    {
        $this->color = $color;

        return $this;
    }

    public function getModel(): ?Model
    {
        return $this->model;
    }

    public function setModel(?Model $model): static
    {
        $this->model = $model;

        return $this;
    }

    public function getScreenSize(): ?ScreenSize
    {
        return $this->screenSize;
    }

    public function setScreenSize(?ScreenSize $screenSize): static
    {
        $this->screenSize = $screenSize;

        return $this;
    }

    public function getScreenResolution(): ?ScreenResolution
    {
        return $this->screenResolution;
    }

    public function setScreenResolution(?ScreenResolution $screenResolution): static
    {
        $this->screenResolution = $screenResolution;

src/Controller/Secure/AboutUsController.php
<?php

namespace App\Controller\Secure;

use App\Entity\AboutUs;
use App\Form\AboutUsType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route("/about-us")]
class AboutUsController extends AbstractController
{
    #[Route("/", name: "about_us")]
    public function index(EntityManagerInterface $em, Request $request): Response
    {
        $arr_about_us = $em->getRepository(AboutUs::class)->findAll();
        if (empty($arr_about_us))
            $about_us = new AboutUs();
        else
            $about_us = $arr_about_us[0];
        $form = $this->createForm(AboutUsType::class, $about_us);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $request->get('about_us');
            $about_us->setDescription($data['description']);
            $em->persist($about_us);
            $em->flush();
            $message['type'] = 'modal';
            $message['alert'] = 'success';
            $message['title'] = 'Éxito';
            $message['message'] = '
                Cambios guardados con éxito
                ';
            $this->addFlash('message', $message);
            return $this->redirectToRoute('about_us');
        }
        $data['title'] = 'Acerca de nosotros';
        $data['breadcrumbs'] = array(
            array('active' => true, 'title' => $data['title'])
        );
        $data['files_js'] = array('ckeditor_text_area.js?v=' . rand());
        $data['form'] = $form->createView();

        return $this->render('secure/about_us/form_about_us.html.twig', $data);
    }
}

src/Controller/Secure/BrandsSectionsController.php
<?php

namespace App\Controller\Secure;

use App\Entity\BrandsSections;
use App\Form\BrandsSectionsType;
use App\Repository\BrandsSectionsRepository;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route("/brands_sections")]
class BrandsSectionsController extends AbstractController
{

    private $pathImg = 'brands';

    #[Route("/", name: "secure_brands_sections_index", methods: ["GET", "POST"])]
    public function new(BrandsSectionsRepository $brandsSections, Request $request, FileUploader $fileUploader, EntityManagerInterface $em): Response
    {

        $data['title'] = 'Marcas';

        $data['breadcrumbs'] = array(
            array('active' => true, 'title' => $data['title'])
        );

        $arr_brands = $brandsSections->findAll();
        if (empty($arr_brands))
            $data['brands'] = new BrandsSections;
        else
            $data['brands'] = $arr_brands[0];

        $form = $this->createForm(BrandsSectionsType::class, $data['brands']);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $brandName1 = $form->get('brandName1')->getData();
            $brandName2 = $form->get('brandName2')->getData();
            $brandName3 = $form->get('brandName3')->getData();
            $brandName4 = $form->get('brandName4')->getData();
            $brandName5 = $form->get('brandName5')->getData();
            $brandName6 = $form->get('brandName6')->getData();
            $brandImage1 = $form->get('brandImage1')->getData();
            $brandImage2 = $form->get('brandImage2')->getData();
            $brandImage3 = $form->get('brandImage3')->getData();
            $brandImage4 = $form->get('brandImage4')->getData();
            $brandImage5 = $form->get('brandImage5')->getData();
            $brandImage6 = $form->get('brandImage6')->getData();


            if (isset($brandImage1)) {
                $imageFileName = $fileUploader->upload($brandImage1, $brandName1, $this->pathImg);
                $data['brands']->setBrandImage1($_ENV['AWS_S3_URL'] . '/' . $this->pathImg . '/' . $imageFileName);
            }
            if (isset($brandImage2)) {
                $imageFileName = $fileUploader->upload($brandImage2, $brandName2, $this->pathImg);
                $data['brands']->setBrandImage2($_ENV['AWS_S3_URL'] . '/' . $this->pathImg . '/' . $imageFileName);
            }
            if (isset($brandImage3)) {
                $imageFileName = $fileUploader->upload($brandImage3, $brandName3, $this->pathImg);
                $data['brands']->setBrandImage3($_ENV['AWS_S3_URL'] . '/' . $this->pathImg . '/' . $imageFileName);
            }
            if (isset($brandImage4)) {
                $imageFileName = $fileUploader->upload($brandImage4, $brandName4, $this->pathImg);
                $data['brands']->setBrandImage4($_ENV['AWS_S3_URL'] . '/' . $this->pathImg . '/' . $imageFileName);
            }
            if (isset($brandImage5)) {
                $imageFileName = $fileUploader->upload($brandImage5, $brandName5, $this->pathImg);
                $data['brands']->setBrandImage5($_ENV['AWS_S3_URL'] . '/' . $this->pathImg . '/' . $imageFileName);
            }
            if (isset($brandImage6)) {
                $imageFileName = $fileUploader->upload($brandImage6, $brandName6, $this->pathImg);
                $data['brands']->setBrandImage6($_ENV['AWS_S3_URL'] . '/' . $this->pathImg . '/' . $imageFileName);
            }

            // $originalImagePath = $_ENV['APP_ENV'] === 'dev' ? 'testing/' . $this->pathImg . '/' . $productNameSlug . '-' . uniqid() . '.jpg' : $this->pathImg . '/' . $productNameSlug . '-' . uniqid() . '.jpg';

            $entityManager = $em;
            $entityManager->persist($data['brands']);
            $entityManager->flush();

            $message['type'] = 'modal';
            $message['alert'] = 'success';
            $message['title'] = 'Éxito';
            $message['message'] = '
                Cambios guardados con éxito
                ';
            $this->addFlash('message', $message);
            return $this->redirectToRoute('secure_brands_sections_index');
        }

        $data['data_img'] = [
            'brandImage1' => $data['brands']->getBrandImage1(),
            'brandImage2' => $data['brands']->getBrandImage2(),
            'brandImage3' => $data['brands']->getBrandImage3(),
            'brandImage4' => $data['brands']->getBrandImage4(),
            'brandImage5' => $data['brands']->getBrandImage5(),
            'brandImage6' => $data['brands']->getBrandImage6(),
        ];

        $data['breadcrumbs'] = array(
            array('active' => true, 'title' => $data['title'])
        );
        $data['form'] = $form;

        return $this->renderForm('secure/brands_sections/brands_sections_form.html.twig', $data);
    }
}

src/Controller/Secure/CurrencyChangeController.php
<?php

namespace App\Controller\Secure;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route("/currency-change", name: "currency_change")]
class CurrencyChangeController extends AbstractController
{
    #[Route("/", name: "currency_change")]
    public function index(): Response
    {
        return $this->render('secure/currency_change/index.html.twig', [
            'controller_name' => 'CurrencyChangeController',
        ]);
    }
}

templates/secure/products/abm_dispatch_products.html.twig
{% extends 'home/index.html.twig' %}
{% block title %}
	{{title}}
{% endblock %}

{% block content %}
	{{parent()}}
	<div class="d-flex justify-content-between">
		<div class="col-6">
			<h1 class="mr-auto mb-0 title-table">{{title}}</h1>
		</div>
		{% if is_granted('ROLE_SUPER_ADMIN') %}
			<div class="col-6 text-end align-self-center">
				<a class="btn btn-success" href="{{ path('secure_product_new_dispatch') }}">Gestionar despacho</a>
			</div>
		{% endif %}
	</div>
	<div class="row">
		<div class="col-xs-12">
			<p>Listar por estados:</p>
		</div>
		<div class="col-xs-12">
			<a href="?status=1" class="btn btn-sm m-2 {{ status == 1 ? 'btn-outline-success':'btn-success' }}">
				{% if is_granted('ROLE_SUPER_ADMIN') %}
					En transito
				{% else %}
					En camino
				{% endif %}
			</a>
			<a href="?status=2" class="btn btn-sm m-2 {{ status == 2 ? 'btn-outline-success':'btn-success' }}">
				Recibidos
			</a>
			<a href="?status=3" class="btn btn-sm m-2 {{ status == 3 ? 'btn-outline-success':'btn-success' }}">
				Cancelados
			</a>
			<a href="?status=all" class="btn btn-sm m-2 {{ status == 'all' ? 'btn-outline-success':'btn-success' }}">
				Todos
			</a>
		</div>
	</div>
	<div class="row mt-5">
		<div class="col-12">
			<div class="table-responsive">
				<table id="table_full_buttons" class="table table-striped table-sm nowrap" data-order="[[2, &quot;asc&quot;]]">
					<thead>
						<tr>
							<th class="text-center" data-orderable="false" style="width:1px"></th>
							<th class="text-center">Orden Despacho Nro</th>
							<th>Punto de venta</th>
							<th>Descripción</th>
							<th>Estado</th>
							<th>Fecha alta</th>
							<th>Ult. Modificación</th>
						</tr>
					</thead>
					<tbody>
						{% for dispatch in dispatches %}
							<tr>
								<td class="text-center" style="width:1px">
									<a href="{{ path("secure_product_show_dispatch",{'dispatch_id':dispatch.id}) }} ">
										<i class="fas fa-eye text-primary"></i>
									</a>
								</td>
								<td class="text-center">{{ dispatch.id }}</td>
								<td>{{ dispatch.salePoint.state.name }}
									-
									{{ dispatch.salePoint.city.name }}</td>
								<td>{{ dispatch.description }}</td>
								<td>{{ dispatch.status.name }}</td>
								<td>{{ dispatch.createdAt|date("d/m/Y", 'America/Argentina/Buenos_Aires') }}</td>
								<td>{{ dispatch.modifiedAt ? dispatch.modifiedAt|date("d/m/Y", 'America/Argentina/Buenos_Aires'):'-' }}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="row mt-5 mb-5">
		<div class="col-12 text-end">
			<a class="btn btn-secondary" href="{{ path('app_homepage') }}">Regresar</a>
		</div>
	</div>
{% endblock %}
{% block javascripts %}
	{{ parent() }}
{% endblock %}

templates/secure/products/abm_products.central.html.twig
{% extends 'home/index.html.twig' %}
{% block title %}
	{{title}}
{% endblock %}

{% block content %}
	{{parent()}}
	<div class="d-flex justify-content-between">
		<div class="col-6">
			<h1 class="mr-auto mb-0 title-table">{{title}}</h1>
		</div>


		<div class="col-6 text-end">
			{% if sale_point is defined %}
				<a class="btn btn-success" href="{{ path('secure_product_new',{"sale_point":"sale_point"}) }}">Nuevo producto</a>
			{% endif %}
		</div>
	</div>
	<div class="row mt-5">
		<div class="col-12">
			<div class="table-responsive">
				<table id="table_full_buttons" class="table table-striped table-sm nowrap" data-order="[[1, &quot;asc&quot;]]">
					<thead>
						<tr>
							<th data-type="num" class="text-center">
								Id. &nbsp;
							</th>
							<th class="text-center">Fecha&nbsp;</th>
							<th class="text-center" data-orderable="false">
								Acciones &nbsp;
							</th>

							<th>COD &nbsp;</th>

							<th class="text-center">Precio &nbsp;</th>

							<th class="text-center">Disponible &nbsp;</th>

							<th>Nombre &nbsp;</th>

							<th>Descripción &nbsp;</th>

							<th>Marca &nbsp;</th>

							<th>Categoría &nbsp;</th>

							<th>Subcategoría &nbsp;</th>

						</tr>
					</thead>
					<tbody>
						{% for product in products %}
							<tr>
								<td class="text-center">
									{{product.id}}
								</td>

								<td data-order="{{product.product.createdAt ? product.product.createdAt|date('U'):0}}" class="text-center">{{product.product.createdAt ? product.product.createdAt|date("d/m/Y", 'America/Argentina/Buenos_Aires'):'-'}}</td>

								<td class="text-center">
									<a style="font-size:16px" class="text-primary m-2" href="{{ path('secure_product_tag',{"product_sale_point_id":product.id}) }}" title="Etiqueta de producto.">
										<i class="fas fa-tag"></i>
									</a>

									<a style="font-size:16px" class="text-{{ product.lastPrice? 'success':'secondary' }} m-2" href="{{ path('secure_product_price',{"product_sale_point_id":product.id}) }}" title="Precio">
										<i class="fas fa-dollar-sign"></i>
									</a>
								</td>

								<td class="text-nowrap">{{product.product.salePoint.role.id == 1? 'A':product.product.salePoint.id}}-{{product.product.cod}}</td>

								<td class="text-center">{{ product.lastPrice ? '$ ' ~ product.lastPrice.price|number_format(2, ',','.') : 'No definido'}}</td>

								<td class="text-center">{{product.lastInventory? product.lastInventory.available:0}}</td>

								<td>{{product.product.name}}</td>

								<td>{{product.product.description}}</td>

								<td>{{ product.product.brand.name}}</td>

								<td>{{product.product.category.name}}</td>

								<td>{{product.product.subcategory ? product.product.subcategory.name:''}}</td>

							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="row mt-5 mb-5">
		<div class="col-12 text-end">
			<a class="btn btn-secondary" href="{{ path('app_homepage') }}">Regresar</a>
		</div>
	</div>
{% endblock %}
{% block javascripts %}
	{{ parent() }}
{% endblock %}

templates/secure/products/abm_products.general.html.twig
{% extends 'home/index.html.twig' %}
{% block title %}
	{{title}}
{% endblock %}

{% block content %}
	{{parent()}}
	<div class="d-flex justify-content-between">
		<div class="col-6">
			<h1 class="mr-auto mb-0 title-table">{{title}}</h1>
		</div>


		<div class="col-6 text-end">
			{% if sale_point is defined %}
				<a class="btn btn-success" href="{{ path('secure_product_new',{"sale_point":"sale_point"}) }}">Nuevo producto</a>
			{% else %}
				<a class="btn btn-success" href="{{ path('secure_product_new') }}">Nuevo producto</a>
			{% endif %}
		</div>
	</div>
	<div class="row mt-5">
		<div class="col-12">
			<div class="table-responsive">
				<table id="table_full_buttons" class="table table-striped table-sm nowrap" data-order="[[1, &quot;asc&quot;]]">
					<thead>
						<tr>
							<th data-type="num" class="text-center">
								Id. &nbsp;
							</th>
							<th class="text-center">Fecha&nbsp;</th>
							<th class="text-center" data-orderable="false">
								Acciones &nbsp;
							</th>

							<th>COD &nbsp;</th>

							<th>Nombre &nbsp;</th>

							<th>Descripción &nbsp;</th>
							
							<th class="text-center">Precio &nbsp;</th>

							<th>Marca &nbsp;</th>

							<th>Categoría &nbsp;</th>

							<th>Subcategoría &nbsp;</th>

						</tr>
					</thead>
					<tbody>
						{% for product in products %}
							<tr>
								<td class="text-center">
									{{product.id}}
								</td>

								<td data-order="{{product.product.createdAt ? product.product.createdAt|date('U'):0}}" class="text-center">{{product.product.createdAt ? product.product.createdAt|date("d/m/Y"):'-'}}</td>

								<td class="text-center">
									<a style="font-size:16px" class="text-primary m-2" href="{{ path('secure_product_tag',{"product_sale_point_id":product.id}) }}" title="Etiqueta de producto.">
										<i class="fas fa-tag"></i>
									</a>

									<a style="font-size:16px" class="text-success m-2" href="{{ path('secure_product_price',{"product_sale_point_id":product.id}) }}" title="Precio">
										<i class="fas fa-dollar-sign"></i>
									</a>
								</td>

								<td>{{product.product.salePoint.role.id == 1? 'A':product.product.salePoint.id}}-{{product.product.cod}}</td>

								<td>{{product.product.name}}</td>

								<td>{{product.product.description}}</td>

								<td class="text-center">{{ product.lastPrice ? '$ ' ~ product.lastPrice.price|number_format(2, ',','.') : 'No definido'}}</td>

								<td>{{ product.product.brand.name}}</td>

								<td>{{product.product.category.name}}</td>

								<td>{{product.product.subcategory ? product.product.subcategory.name:''}}</td>

							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="row mt-5 mb-5">
		<div class="col-12 text-end">
			<a class="btn btn-secondary" href="{{ path('app_homepage') }}">Regresar</a>
		</div>
	</div>
{% endblock %}
{% block javascripts %}
	{{ parent() }}
{% endblock %}