src/Entity/Orders.php
<?php

namespace App\Entity;

use App\Repository\OrdersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrdersRepository::class)]
class Orders
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    private $id;

    #[ORM\ManyToOne(targetEntity: Customer::class, inversedBy: "orders")]
    #[ORM\JoinColumn(nullable: false)]
    private $customer;

    #[ORM\Column(type: "string", length: 255)]
    private $customer_name;

    #[ORM\Column(type: "string", length: 255)]
    private $customer_email;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    private $code_area_phone_customer;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    private $phone_customer;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    private $customer_identity_number;

    #[ORM\ManyToOne(targetEntity: States::class, inversedBy: "orders")]
    #[ORM\JoinColumn(nullable: true)]
    private $customer_state;

    #[ORM\ManyToOne(targetEntity: Cities::class, inversedBy: "orders")]
    #[ORM\JoinColumn(nullable: true)]
    private $customer_city;

    #[ORM\Column(type: "text", nullable: true)]
    private $customer_street_address;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    private $customer_postal_code;

    #[ORM\Column(type: "text", nullable: true)]
    private $customer_number_address;

    #[ORM\Column(type: "text", nullable: true)]
    private $customer_floor_apartment;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    private $bill_file;

    #[ORM\Column(type: "float", nullable: true)]
    private $total_order;

    #[ORM\ManyToOne(targetEntity: StatusOrderType::class, inversedBy: "orders")]
    #[ORM\JoinColumn(nullable: false)]
    private $status;

    #[ORM\OneToMany(targetEntity: OrdersProducts::class, mappedBy: "order_number", cascade: ["remove"])]
    private $ordersProducts;

    #[ORM\Column(type: "datetime", nullable: false)]
    private $created_at;

    #[ORM\OneToMany(targetEntity: PaymentsFiles::class, mappedBy: "order_number", cascade: ["remove"])]
    private $paymentsFiles;

    #[ORM\ManyToOne(inversedBy: 'number_order')]
    #[ORM\JoinColumn(nullable: false)]
    private ?PaymentType $paymentType = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $sale_point = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $modified_at = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?ShippingType $shipping_type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tracking_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tracking_number = null;

    public function __construct()
    {
        $this->ordersProducts = new ArrayCollection();
        $this->paymentsFiles = new ArrayCollection();
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    public function getCustomerName(): ?string
    {
        return $this->customer_name;
    }

    public function setCustomerName(string $customer_name): self
    {
        $this->customer_name = $customer_name;

        return $this;
    }

    public function getCustomerEmail(): ?string
    {
        return $this->customer_email;
    }

    public function setCustomerEmail(string $customer_email): self
    {
        $this->customer_email = $customer_email;

        return $this;
    }

    public function getCodeAreaPhoneCustomer(): ?string
    {
        return $this->code_area_phone_customer;
    }

    public function setCodeAreaPhoneCustomer(string $code_area_phone_customer): self
    {
        $this->code_area_phone_customer = $code_area_phone_customer;

        return $this;
    }

    public function getPhoneCustomer(): ?string
    {
        return $this->phone_customer;
    }

    public function setPhoneCustomer(?string $phone_customer): self
    {
        $this->phone_customer = $phone_customer;

        return $this;
    }

    public function getCustomerIdentityNumber(): ?string
    {
        return $this->customer_identity_number;
    }

    public function setCustomerIdentityNumber(string $customer_identity_number): self
    {
        $this->customer_identity_number = $customer_identity_number;

        return $this;
    }

    public function getBillFile(): ?string
    {
        return $this->bill_file;
    }

    public function setBillFile(?string $bill_file): self
    {
        $this->bill_file = $bill_file;

        return $this;
    }

    public function getCustomerState(): ?States
    {
        return $this->customer_state;
    }

    public function setCustomerState(?States $customer_state): self
    {
        $this->customer_state = $customer_state;

        return $this;
    }

    public function getCustomerCity(): ?Cities
    {
        return $this->customer_city;
    }

    public function setCustomerCity(?Cities $customer_city): self
    {
        $this->customer_city = $customer_city;

        return $this;
    }

    public function getCustomerStreetAddress(): ?string
    {
        return $this->customer_street_address;
    }

    public function setCustomerStreetAddress(string $customer_street_address): self
    {
        $this->customer_street_address = $customer_street_address;

        return $this;
    }

    public function getCustomerPostalCode(): ?string
    {
        return $this->customer_postal_code;
    }

    public function setCustomerPostalCode(string $customer_postal_code): self
    {
        $this->customer_postal_code = $customer_postal_code;

        return $this;
    }

    public function getCustomerNumberAddress(): ?string
    {
        return $this->customer_number_address;
    }

    public function setCustomerNumberAddress(?string $customer_number_address): self
    {
        $this->customer_number_address = $customer_number_address;

        return $this;
    }

    public function getCustomerFloorApartment(): ?string
    {
        return $this->customer_floor_apartment;
    }

    public function setCustomerFloorApartment(?string $customer_floor_apartment): self
    {
        $this->customer_floor_apartment = $customer_floor_apartment;

        return $this;
    }

    public function getTotalOrder(): ?float
    {
        return $this->total_order;
    }

    public function setTotalOrder(float $total_order): self
    {
        $this->total_order = $total_order;

        return $this;
    }

    public function getStatus(): ?StatusOrderType
    {
        return $this->status;
    }

    public function setStatus(?StatusOrderType $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, OrdersProducts>
     */
    public function getOrdersProducts(): Collection
    {
        return $this->ordersProducts;
    }

    public function addOrdersProduct(OrdersProducts $ordersProduct): self
    {
        if (!$this->ordersProducts->contains($ordersProduct)) {
            $this->ordersProducts[] = $ordersProduct;
            $ordersProduct->setOrderNumber($this);
        }

        return $this;
    }

    public function removeOrdersProduct(OrdersProducts $ordersProduct): self
    {
        if ($this->ordersProducts->removeElement($ordersProduct)) {
            // set the owning side to null (unless already changed)
            if ($ordersProduct->getOrderNumber() === $this) {
                $ordersProduct->setOrderNumber(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function generateOrder()
    {
        $orders_products_array = $this->ordersProducts;
        $orders_products_result = [];
        foreach ($orders_products_array as $order_product) {
            $orders_products_result[] = [
                'product_name' => $order_product->getName(),
                'quantity' => $order_product->getQuantity(),
                'code' => $order_product->getCod(),
                'price' => $order_product->getPrice(),
            ];
        }


        $payments_files_array = $this->paymentsFiles;
        $payments_files_result = [];

        foreach ($payments_files_array as $paymentFile) {
            $payments_files_result[] = [
                "id" => $paymentFile->getId(),
                "payment_file" => $paymentFile->getPaymentFile(),
                "created_at" => $paymentFile->getCreatedAt(),
            ];
        }

        return [
            "order_id" => $this->getId(),
            "created_at" => $this->getCreatedAt()->format('Y-m-d H:i:s'),
            "status_order_name" => $this->getStatus()->getName(),
            "status_order_id" => $this->getStatus()->getId(),
            "products" => $orders_products_result,
            "order_data" => [
                "name" => $this->getCustomerName(),
                "email" => $this->getCustomerEmail(),
                "identity_number" => $this->getCustomerIdentityNumber(),
                "code_area" => $this->getCodeAreaPhoneCustomer(),
                "phone" => $this->getPhoneCustomer(),
                "state_id" => $this->getCustomerState()->getId(),
                "state_name" => $this->getCustomerState()->getName(),
                "city_id" => $this->getCustomerCity()->getId(),

src/Controller/Secure/AboutUsController.php
<?php

namespace App\Controller\Secure;

use App\Entity\AboutUs;
use App\Form\AboutUsType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route("/about-us")]
class AboutUsController extends AbstractController
{
    #[Route("/", name: "about_us")]
    public function index(EntityManagerInterface $em, Request $request): Response
    {
        $arr_about_us = $em->getRepository(AboutUs::class)->findAll();
        if (empty($arr_about_us))
            $about_us = new AboutUs();
        else
            $about_us = $arr_about_us[0];
        $form = $this->createForm(AboutUsType::class, $about_us);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $request->get('about_us');
            $about_us->setDescription($data['description']);
            $em->persist($about_us);
            $em->flush();
            $message['type'] = 'modal';
            $message['alert'] = 'success';
            $message['title'] = 'Éxito';
            $message['message'] = '
                Cambios guardados con éxito
                ';
            $this->addFlash('message', $message);
            return $this->redirectToRoute('about_us');
        }
        $data['title'] = 'Acerca de nosotros';
        $data['breadcrumbs'] = array(
            array('active' => true, 'title' => $data['title'])
        );
        $data['files_js'] = array('ckeditor_text_area.js?v=' . rand());
        $data['form'] = $form->createView();

        return $this->render('secure/about_us/form_about_us.html.twig', $data);
    }
}

src/Controller/Secure/BrandsSectionsController.php
<?php

namespace App\Controller\Secure;

use App\Entity\BrandsSections;
use App\Form\BrandsSectionsType;
use App\Repository\BrandsSectionsRepository;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route("/brands_sections")]
class BrandsSectionsController extends AbstractController
{

    private $pathImg = 'brands';

    #[Route("/", name: "secure_brands_sections_index", methods: ["GET", "POST"])]
    public function new(BrandsSectionsRepository $brandsSections, Request $request, FileUploader $fileUploader, EntityManagerInterface $em): Response
    {

        $data['title'] = 'Marcas';

        $data['breadcrumbs'] = array(
            array('active' => true, 'title' => $data['title'])
        );

        $arr_brands = $brandsSections->findAll();
        if (empty($arr_brands))
            $data['brands'] = new BrandsSections;
        else
            $data['brands'] = $arr_brands[0];

        $form = $this->createForm(BrandsSectionsType::class, $data['brands']);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $brandName1 = $form->get('brandName1')->getData();
            $brandName2 = $form->get('brandName2')->getData();
            $brandName3 = $form->get('brandName3')->getData();
            $brandName4 = $form->get('brandName4')->getData();
            $brandName5 = $form->get('brandName5')->getData();
            $brandName6 = $form->get('brandName6')->getData();
            $brandImage1 = $form->get('brandImage1')->getData();
            $brandImage2 = $form->get('brandImage2')->getData();
            $brandImage3 = $form->get('brandImage3')->getData();
            $brandImage4 = $form->get('brandImage4')->getData();
            $brandImage5 = $form->get('brandImage5')->getData();
            $brandImage6 = $form->get('brandImage6')->getData();


            if (isset($brandImage1)) {
                $imageFileName = $fileUploader->upload($brandImage1, $brandName1, $this->pathImg);
                $data['brands']->setBrandImage1($_ENV['AWS_S3_URL'] . '/' . $this->pathImg . '/' . $imageFileName);
            }
            if (isset($brandImage2)) {
                $imageFileName = $fileUploader->upload($brandImage2, $brandName2, $this->pathImg);
                $data['brands']->setBrandImage2($_ENV['AWS_S3_URL'] . '/' . $this->pathImg . '/' . $imageFileName);
            }
            if (isset($brandImage3)) {
                $imageFileName = $fileUploader->upload($brandImage3, $brandName3, $this->pathImg);
                $data['brands']->setBrandImage3($_ENV['AWS_S3_URL'] . '/' . $this->pathImg . '/' . $imageFileName);
            }
            if (isset($brandImage4)) {
                $imageFileName = $fileUploader->upload($brandImage4, $brandName4, $this->pathImg);
                $data['brands']->setBrandImage4($_ENV['AWS_S3_URL'] . '/' . $this->pathImg . '/' . $imageFileName);
            }
            if (isset($brandImage5)) {
                $imageFileName = $fileUploader->upload($brandImage5, $brandName5, $this->pathImg);
                $data['brands']->setBrandImage5($_ENV['AWS_S3_URL'] . '/' . $this->pathImg . '/' . $imageFileName);
            }
            if (isset($brandImage6)) {
                $imageFileName = $fileUploader->upload($brandImage6, $brandName6, $this->pathImg);
                $data['brands']->setBrandImage6($_ENV['AWS_S3_URL'] . '/' . $this->pathImg . '/' . $imageFileName);
            }

            // $originalImagePath = $_ENV['APP_ENV'] === 'dev' ? 'testing/' . $this->pathImg . '/' . $productNameSlug . '-' . uniqid() . '.jpg' : $this->pathImg . '/' . $productNameSlug . '-' . uniqid() . '.jpg';

            $entityManager = $em;
            $entityManager->persist($data['brands']);
            $entityManager->flush();

            $message['type'] = 'modal';
            $message['alert'] = 'success';
            $message['title'] = 'Éxito';
            $message['message'] = '
                Cambios guardados con éxito
                ';
            $this->addFlash('message', $message);
            return $this->redirectToRoute('secure_brands_sections_index');
        }

        $data['data_img'] = [
            'brandImage1' => $data['brands']->getBrandImage1(),
            'brandImage2' => $data['brands']->getBrandImage2(),
            'brandImage3' => $data['brands']->getBrandImage3(),
            'brandImage4' => $data['brands']->getBrandImage4(),
            'brandImage5' => $data['brands']->getBrandImage5(),
            'brandImage6' => $data['brands']->getBrandImage6(),
        ];

        $data['breadcrumbs'] = array(
            array('active' => true, 'title' => $data['title'])
        );
        $data['form'] = $form;

        return $this->renderForm('secure/brands_sections/brands_sections_form.html.twig', $data);
    }
}

src/Controller/Secure/CurrencyChangeController.php
<?php

namespace App\Controller\Secure;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route("/currency-change", name: "currency_change")]
class CurrencyChangeController extends AbstractController
{
    #[Route("/", name: "currency_change")]
    public function index(): Response
    {
        return $this->render('secure/currency_change/index.html.twig', [
            'controller_name' => 'CurrencyChangeController',
        ]);
    }
}

templates/secure/orders/form_order_products_list.html.twig
{% extends 'home/index.html.twig' %}
{% block title %}
	{{title}}
{% endblock %}

{% block content %}
	{{parent()}}
	<div class="d-flex justify-content-between">
		<div class="col-12">
			<h1 class="mr-auto mb-0 title-table">{{title}}
				Nro:
				{{order.id}}</h1>
			<p>
				<b>Punto de venta:</b>
				{{order.salePoint.state.name}}
				-{{order.salePoint.city.name}}
			</p>
		</div>
	</div>
	<div class="row">
		<div class="col-4">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th colspan="3" class="p-3 text-end">
							<a href=" {{ path('secure_order_payment_file',{'order_id':order.id}) }} " class="btn btn-success">
								Cargar comprobante
							</a>
						</th>
					</tr>
					<tr>
						<th>
							Comprobantes de pago
						</th>
						<th>
							Monto
						</th>
						<th>
							Fecha
						</th>
					</tr>
				</thead>
				<tbody>
					{% if not order.paymentsFiles %}
						<td colspan="3" class="text-center">No hay comprobantes de pagos cargados</td>
					{% else %}
						{% for payment_file in order.paymentsFiles %}
							<tr>
								<td>
									<a href="{{ payment_file.paymentFile }}" target="_blank">Descargar comprobante</a>
								</td>
								<td>
									$
									{{ payment_file.amount|number_format(2,',','.') }}
								</td>
								<td>
									{{ payment_file.datePaid|date('d/m/Y', 'America/Argentina/Buenos_Aires') }}
								</td>
							</tr>
						{% endfor %}
					{% endif %}
				</tbody>
			</table>
		</div>
		<div class="col-4"></div>
		<div class="col-4">
			<table class="table table-bordered">
				<tbody>
					<tr>
						<th class="text-end">
							Estado:
						</th>
						<td>
							{{order.status.name}}
						</td>
					</tr>
					<tr>
						<th class="text-end">
							Fecha de creación:
						</th>
						<td>
							{{ order.createdAt|date('d/m/Y H:i:s', 'America/Argentina/Buenos_Aires') }}
						</td>
					</tr>
					<tr>
						<th class="text-end">
							Forma de pago:
						</th>
						<td>
							{{ order.paymentType.name }}
						</td>
					</tr>
					<tr>
						<th class="text-end">
							Orden de venta:
						</th>
						<td>
							<a href="{{ order.billFile }}" target="_blank">
								<i class="far fa-file-pdf text-danger"></i>
							</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>

		{{ form_start (form) }}

		{% if form_errors (form) %}
			<div class="col-12">
				<div class="alert alert-danger">
					{{ form_errors (form) }}
				</div>
			</div>
		{% endif %}
		<div class="col-12 my-2">
			<table id="table_simple" data-paging="false" class="table table-striped table-sm" data-order="[[2, &quot;desc&quot;]]">
				<thead>
					<tr>
						<th>COD</th>
						<th>Producto</th>
						<th class="text-center">Cantidad</th>
						<th class="text-center">Precio unitario</th>
						<th class="text-center">Subtotal</th>
						<th>Marca</th>
						<th>Categoría</th>
						<th>Subcategoría</th>
					</tr>
				</thead>
				<tbody>
					{% for product in order.ordersProducts %}
						<tr>
							<td class="text-nowrap">{{product.productsSalesPoints.product.salePoint.role.id == 1? 'A':product.productsSalesPoints.product.salePoint.id}}-{{product.productsSalesPoints.product.cod}}</td>
							<td>{{ product.productsSalesPoints.product.name }}</td>
							<td class="text-center">
								{{ product.quantity}}
							</td>
							<td class="text-center">
								$
								{{ product.price|number_format(2,',','.') }}
							</td>
							<td class="text-center">
								$
								{{ (product.quantity * product.price)|number_format(2,',','.') }}
							</td>
							<td>{{ product.productsSalesPoints.product.brand.name }}</td>
							<td>{{ product.productsSalesPoints.product.category.name }}</td>
							<td>{{ product.productsSalesPoints.product.subcategory ? product.productsSalesPoints.product.subcategory.name:'' }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="col-12 mb-5 px-5 d-flex flex-row-reverse text-end">
			<table>
				<tbody>
					<tr>
						<th class="px-3" style="font-size:18px;">Subtotal:</th>
						<td class="px-3" style="font-size:18px;">$
							{{ order.totalOrder|number_format(2,',','.') }}</td>
					</tr>
					<tr>
						<th class="px-3" style="font-size:18px;">Descuento:</th>
						<td class="px-3" style="font-size:18px;">$ 0,00</td>
					</tr>
					<tr style="border-top:solid 1px black">
						<th class="px-3" style="font-size:18px;">Total:</th>
						<td class="px-3" style="font-size:18px;">$
							{{ order.totalOrder|number_format(2,',','.') }}</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="row">
			<div class="col-12 my-2">
				{{ form_label (form.status) }}
				{{ form_widget (form.status) }}
				{{ form_errors (form.status)}}
			</div>
		</div>
		<div class="row" id="shippingTypeDiv" style="display:none">
			<div class="col-12 my-2">
				{{ form_label (form.shipping_type) }}
				{{ form_widget (form.shipping_type) }}
				{{ form_errors (form.shipping_type)}}
			</div>
		</div>
		<div class="row" id="trackingDataDiv" style="display:none">
			<div class="col-6">
				{{ form_label (form.tracking_name) }}
				{{ form_widget (form.tracking_name) }}
				{{ form_errors (form.tracking_name)}}
			</div>
			<div class="col-6">
				{{ form_label (form.tracking_number) }}
				{{ form_widget (form.tracking_number) }}
				{{ form_errors (form.tracking_number)}}
			</div>
		</div>
		<div class="row my-5">
			<div class="col-12 text-end">
				<a class="btn btn-secondary" href="{{ path('secure_order_index') }}">Regresar</a>

				<button class="btn btn-success btn-save-inputs-datatable">Guardar</button>
			</div>
		</div>
		{{ form_end (form) }}
	</div>
{% endblock %}
{% block javascripts %}
	{{ parent() }}
{% endblock %}

templates/secure/orders/form_payment_file.html.twig
{% extends 'home/index.html.twig' %}
{% block title %}
	{{title}}
{% endblock %}

{% block content %}
	{{parent()}}
	<div class="d-flex justify-content-between">
		<div class="col-6">
			<h1 class="mr-auto mb-0 title-table">{{title}}
				orden Nro:
				{{order.id}}</h1>
		</div>

	</div>
	{{ form_start (form) }}
	<div class="row">

		{% if form_errors (form) %}
			<div class="col-12">
				<div class="alert alert-danger">
					{{ form_errors (form) }}
				</div>
			</div>
		{% endif %}
	</div>
	<div class="row">
		<div class="col-3 my-2">
			{{ form_label (form.payment_file) }}
			{{ form_widget (form.payment_file) }}
			{{ form_errors (form.payment_file)}}
		</div>
	</div>
	<div class="row">
		<div class="col-3 my-2">
			{{ form_label (form.amount) }}
			{{ form_widget (form.amount) }}
			{{ form_errors (form.amount)}}
		</div>
	</div>
	<div class="row">
		<div class="col-3 my-2">
			{{ form_label (form.date_paid) }}
			{{ form_widget (form.date_paid) }}
			{{ form_errors (form.date_paid)}}
		</div>
	</div>
	<div class="row my-5">
		<div class="col-3 text-end">
			<a class="btn btn-secondary" href="{{ path('secure_order_show',{'order_id':order.id}) }}">Regresar</a>

			<button class="btn btn-success btn-save-inputs-datatable">Guardar</button>
		</div>
	</div>
	{{ form_end (form) }}
	{{ form_end (form) }}
{% endblock %}
{% block javascripts %}
	{{ parent() }}
{% endblock %}

templates/secure/orders/orders_list.html.twig
{% extends 'home/index.html.twig' %}
{% block title %}
	{{title}}
{% endblock %}

{% block content %}
	{{parent()}}
	<div class="d-flex justify-content-between">
		<div class="col-6">
			<h1 class="mr-auto mb-0 title-table">{{title}}</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<p>Listar por estados:</p>
		</div>
		<div class="col-xs-12">
			<a href="?status=1" class="btn btn-sm m-2 {{ status == 1 ? 'btn-outline-success':'btn-success' }}">
				Abierta
			</a>
			<a href="?status=2" class="btn btn-sm m-2 {{ status == 2 ? 'btn-outline-success':'btn-success' }}">
				Confirmadas
			</a>
			<a href="?status=3" class="btn btn-sm m-2 {{ status == 3 ? 'btn-outline-success':'btn-success' }}">
				Canceladas
			</a>
			<a href="?status=all" class="btn btn-sm m-2 {{ status == 'all' ? 'btn-outline-success':'btn-success' }}">
				Todos
			</a>
		</div>
	</div>
	<div class="row mt-5">
		<div class="col-12">
			<div class="table-responsive">
				<table id="table_full_buttons" class="table table-striped table-sm nowrap" data-order="[[0, &quot;asc&quot;]]">
					<thead>
						<tr>
							<th class="text-center" style="width:1px">Orden Nro</th>
							<th class="text-center" data-orderable="false" style="width:1px"></th>
							<th data-orderable="false">Orden de venta</th>
							<th>Fecha alta</th>
							<th style="width:5px">Estado</th>
							<th>Total orden</th>
							{% if is_granted('ROLE_SUPER_ADMIN') %}
								<th>Punto de venta</th>
							{% endif %}
							<th>Cliente</th>
							<th>Tel</th>
							<th>Dirección</th>
							<th>Forma de pago</th>
						</tr>
					</thead>
					<tbody>
						{% for order in orders %}
							<tr>
								<td class="text-center" style="width:1px">{{ order.id }}</td>
								<td class="text-center" style="width:1px">
									<a href="{{ path('secure_order_show',{"order_id":order.id}) }}">
										<i class="fas fa-eye text-primary"></i>
									</a>
								</td>
								<td class="text-center" style="width:5px">
									<a href="{{ order.billFile }}" target="_blank">
										<i class="far fa-file-pdf text-danger"></i>
									</a>
								</td>
								<td>{{ order.createdAt|date("d/m/Y", 'America/Argentina/Buenos_Aires') }}</td>
								<td style="width:5px">{{ order.status.name }}</td>
								<td style="width:5px" class="text-center">$
									{{ order.totalOrder|number_format(2, ',', '.') }}</td>
									{% if is_granted('ROLE_SUPER_ADMIN') %}
										<td>{{ order.salePoint.state.name }} - {{ order.salePoint.city.name }}</td>
									{% endif %}
								<td>{{ order.customer.name }}</td>
								<td>
									<a href="tel:+549{{ order.codeAreaPhoneCustomer ~ order.phoneCustomer }}">{{ order.codeAreaPhoneCustomer ~ order.phoneCustomer }}</td>
								</td>
								<td>{{ order.customerStreetAddress }}
									{{ order.customerNumberAddress }}
									{{ order.customerFloorApartment }}
									(C.P
									{{ order.customerPostalCode }}),
									{{order.customerState? order.customerState.name:''}},
									{{order.customerCity? order.customerCity.name:''}}
								</td>
								<td>{{ order.paymentType.name }}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="row mt-5 mb-5">
		<div class="col-12 text-end">
			<a class="btn btn-secondary" href="{{ path('app_homepage') }}">Regresar</a>
		</div>
	</div>
{% endblock %}
{% block javascripts %}
	{{ parent() }}
{% endblock %}