src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Model\User as BaseUser;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: "App\Repository\UserRepository")]
#[ORM\Table(name: "mia_user")]
#[UniqueEntity("email")]
class User extends BaseUser
{
    #[ORM\Column(type: "string")]
    protected $roles = [];

    #[ORM\Column(name: "password", type: "string", length: 512, nullable: true)]
    protected $password;

    #[ORM\ManyToOne(targetEntity: Roles::class, inversedBy: "users")]
    private $role;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    private ?States $state = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cities $city = null;

    #[ORM\Column(options: ["default" => 1])]
    private ?bool $active = null;

    #[ORM\Column(type: "boolean", options: ["default" => 0])]
    private bool $change_password = false;

    #[ORM\Column(type: "datetime", nullable: true)]
    private ?\DateTimeInterface $change_password_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $verification_code = null;

    #[ORM\Column(length: 255, options: ['default' => ''])]
    private ?string $street_address = '';

    #[ORM\Column(length: 20, options: ['default' => ''])]
    private ?string $number_address = '';

    #[ORM\Column(options: ['default' => true])]
    private ?bool $visible = true;

    #[ORM\OneToMany(mappedBy: 'sale_point', targetEntity: Product::class)]
    private Collection $products;

    #[ORM\OneToMany(mappedBy: 'sale_point', targetEntity: ProductsSalesPoints::class)]
    private Collection $productsSalesPoints;

    #[ORM\OneToMany(mappedBy: 'sale_point', targetEntity: Dispatch::class)]
    private Collection $dispatches;

    #[ORM\OneToMany(mappedBy: 'sale_point', targetEntity: Orders::class)]
    private Collection $orders;

    public function __construct()
    {
        parent::__construct();
        $this->change_password = false;
        $this->active = true;
        $this->visible = true;
        $this->street_address = '';
        $this->number_address = '';
        $this->products = new ArrayCollection();
        $this->productsSalesPoints = new ArrayCollection();
        $this->dispatches = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    public function getRoles(): array
    {
        return array_unique([$this->role->getRole()]);
    }

    public function getRole(): ?Roles
    {
        return $this->role;
    }

    public function setRole(?Roles $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function setPassword(?string $password): self
    {
        $this->password = password_hash($password, PASSWORD_BCRYPT);

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function getState(): ?States
    {
        return $this->state;
    }

    public function setState(?States $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getCity(): ?Cities
    {
        return $this->city;
    }

    public function setCity(?Cities $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): static
    {
        $this->active = $active;

        return $this;
    }

    public function isChangePassword(): ?bool
    {
        return $this->change_password;
    }

    public function setChangePassword(bool $change_password): static
    {
        $this->change_password = $change_password;

        return $this;
    }

    public function getChangePasswordDate(): ?\DateTimeInterface
    {
        return $this->change_password_date;
    }

    public function setChangePasswordDate(?\DateTimeInterface $change_password_date): static
    {
        $this->change_password_date = $change_password_date;

        return $this;
    }

    public function getVerificationCode(): ?string
    {
        return $this->verification_code;
    }

    public function setVerificationCode(?string $verification_code): static
    {
        $this->verification_code = $verification_code;

        return $this;
    }

    public function getStreetAddress(): ?string
    {
        return $this->street_address;
    }

    public function setStreetAddress(string $street_address): static
    {
        $this->street_address = $street_address;

        return $this;
    }

    public function getNumberAddress(): ?string
    {
        return $this->number_address;
    }

    public function setNumberAddress(string $number_address): static
    {
        $this->number_address = $number_address;

        return $this;
    }

    public function isVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): static
    {
        $this->visible = $visible;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setSalePoint($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): static
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getSalePoint() === $this) {
                $product->setSalePoint(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ProductsSalesPoints>
     */
    public function getProductsSalesPoints(): Collection
    {
        return $this->productsSalesPoints;
    }

    public function addProductsSalesPoint(ProductsSalesPoints $productsSalesPoint): static
    {
        if (!$this->productsSalesPoints->contains($productsSalesPoint)) {
            $this->productsSalesPoints->add($productsSalesPoint);
            $productsSalesPoint->setSalePoint($this);
        }

        return $this;
    }

    public function removeProductsSalesPoint(ProductsSalesPoints $productsSalesPoint): static
    {
        if ($this->productsSalesPoints->removeElement($productsSalesPoint)) {
            // set the owning side to null (unless already changed)
            if ($productsSalesPoint->getSalePoint() === $this) {
                $productsSalesPoint->setSalePoint(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Dispatch>
     */
    public function getDispatches(): Collection
    {
        return $this->dispatches;
    }

    public function addDispatch(Dispatch $dispatch): static
    {
        if (!$this->dispatches->contains($dispatch)) {
            $this->dispatches->add($dispatch);
            $dispatch->setSalePoint($this);
        }

        return $this;
    }

    public function removeDispatch(Dispatch $dispatch): static
    {
        if ($this->dispatches->removeElement($dispatch)) {
            // set the owning side to null (unless already changed)
            if ($dispatch->getSalePoint() === $this) {
                $dispatch->setSalePoint(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Orders>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Orders $order): static
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setSalePoint($this);
        }

        return $this;
    }

    public function removeOrder(Orders $order): static
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getSalePoint() === $this) {
                $order->setSalePoint(null);
            }
        }

        return $this;
    }
}

src/Controller/Secure/AboutUsController.php
<?php

namespace App\Controller\Secure;

use App\Entity\AboutUs;
use App\Form\AboutUsType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route("/about-us")]
class AboutUsController extends AbstractController
{
    #[Route("/", name: "about_us")]
    public function index(EntityManagerInterface $em, Request $request): Response
    {
        $arr_about_us = $em->getRepository(AboutUs::class)->findAll();
        if (empty($arr_about_us))
            $about_us = new AboutUs();
        else
            $about_us = $arr_about_us[0];
        $form = $this->createForm(AboutUsType::class, $about_us);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $request->get('about_us');
            $about_us->setDescription($data['description']);
            $em->persist($about_us);
            $em->flush();
            $message['type'] = 'modal';
            $message['alert'] = 'success';
            $message['title'] = 'Éxito';
            $message['message'] = '
                Cambios guardados con éxito
                ';
            $this->addFlash('message', $message);
            return $this->redirectToRoute('about_us');
        }
        $data['title'] = 'Acerca de nosotros';
        $data['breadcrumbs'] = array(
            array('active' => true, 'title' => $data['title'])
        );
        $data['files_js'] = array('ckeditor_text_area.js?v=' . rand());
        $data['form'] = $form->createView();

        return $this->render('secure/about_us/form_about_us.html.twig', $data);
    }
}

src/Controller/Secure/ApiClientsController.php
<?php

namespace App\Controller\Secure;

use DateTime;
use App\Entity\ApiClients;
use App\Form\ApiClientsType;
use Symfony\Component\Uid\Uuid;
use App\Repository\ApiClientsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route("/api_clients")]
class ApiClientsController extends AbstractController
{


    #[Route("/", name: "api_clients")]
    public function index(ApiClientsRepository $apiClientsRepository): Response
    {
        $data['title'] = 'Usuarios API';
        $data['api_clients'] = $apiClientsRepository->findAll();
        $data['files_js'] = array('table_full_buttons.js?v=' . rand());
        $data['breadcrumbs'] = array(
            array('active' => true, 'title' => $data['title'])
        );
        return $this->render('secure/api_clients/abm_api_clients.html.twig', $data);
    }

    #[Route("/new", name: "new_api_clients")]
    public function new(Request $request, EntityManagerInterface $em): Response
    {
        $data['title'] = "Nuevo usuario API";
        $data['api_client'] = new ApiClients();
        $form = $this->createForm(ApiClientsType::class, $data['api_client']);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $clave['api_client_id'] = Uuid::v1();
            $clave['api_key'] = Uuid::v4();
            $data['api_client']->setApiClientId($clave['api_client_id']);
            $data['api_client']->setApiKey($clave['api_key']);
            $data['api_client']->setCreatedAt(new \DateTime());


            $entityManager = $em;
            $entityManager->persist($data['api_client']);
            $entityManager->flush();

            $message['type'] = 'modal';
            $message['alert'] = 'success';
            $message['size'] = 'modal-xl';
            $message['title'] = 'Se creó un nuevo usuario de API';
            $message['message'] = '
                A continuación se detalla las credenciales del usuario creado<br>
                <br>
                Anotelas ya que no podrá volver a consultarlas, en caso de olvido o pérdida deberá reiniciar la api key.<br>
                <br>
                <span class="fw-bold">API Client: </span>' . $data['api_client']->getName() . '
                <br>
                <span class="fw-bold">Rol: </span>' . $data['api_client']->getApiClientTypeRole()->getName() . '
                <br>
                <span class="fw-bold">Authentication: </span> Basic
                <br>               
                <span class="fw-bold">Username: </span> ' . $clave['api_client_id'] . '
                <br>
                <span class="fw-bold">Password: </span> ' . $clave['api_key'] . '
                <br>
                <span class="fw-bold">Clave encriptada: </span> ' . base64_encode($clave['api_client_id'] . ':' . $clave['api_key']) . '
                <br>
                ';
            $this->addFlash('message', $message);
            return $this->redirectToRoute('api_clients', [], Response::HTTP_SEE_OTHER);
        }

        $data['form'] = $form;
        $data['breadcrumbs'] = array(
            array('path' => 'api_clients', 'title' => 'Usuarios API'),
            array('active' => true, 'title' => $data['title'])
        );
        return $this->renderForm('secure/api_clients/form_api_clients.html.twig', $data);
    }

    #[Route("/{id}/edit", name: "edit_api_clients")]
    public function edit($id, Request $request, ApiClientsRepository $apiClientsRepository, EntityManagerInterface $em): Response
    {
        $data['reset_api_key'] = true;
        $data['title'] = "Editar usuario API";
        $data['api_client'] = $apiClientsRepository->find($id);
        $form = $this->createForm(ApiClientsType::class, $data['api_client']);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if ($form->get('reset_api_key')->getData()) {
                $clave['api_key'] = Uuid::v4();
                $data['api_client']->setApiKey($clave['api_key']);
                $message['type'] = 'modal';
                $message['alert'] = 'success';
                $message['size'] = 'modal-xl';
                $message['title'] = 'Se editó usuario de API';
                $message['message'] = '
                    A continuación se detalla las credenciales del usuario editado<br>
                    <br>
                    Anotelas ya que no podrá volver a consultarlas, en caso de olvido o pérdida deberá reiniciar la api key.<br>
                    <br>
                    <span class="fw-bold">API Client: </span>' . $data['api_client']->getName() . '
                    <br>
                    <span class="fw-bold">Rol: </span>' . $data['api_client']->getApiClientTypeRole()->getName() . '
                    <br>                
                    <span class="fw-bold">Authentication: </span> Basic
                    <br>                
                    <span class="fw-bold">Username: </span> ' . $data['api_client']->getApiClientId() . '
                    <br>
                    <span class="fw-bold">Password: </span> ' . $clave['api_key'] . '
                    <br>
                    <span class="fw-bold">Clave encriptada: </span> ' . base64_encode($data['api_client']->getApiClientId() . ':' . $clave['api_key']) . '
                    <br>
                    ';
                $this->addFlash('message', $message);
            }
            $entityManager = $em;
            $entityManager->persist($data['api_client']);
            $entityManager->flush();

            return $this->redirectToRoute('api_clients', [], Response::HTTP_SEE_OTHER);
        }

        $data['form'] = $form;
        $data['breadcrumbs'] = array(
            array('path' => 'api_clients', 'title' => 'Usuarios API'),
            array('active' => true, 'title' => $data['title'])
        );
        return $this->renderForm('secure/api_clients/form_api_clients.html.twig', $data);
    }
}

src/Controller/Secure/CurrencyChangeController.php
<?php

namespace App\Controller\Secure;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route("/currency-change", name: "currency_change")]
class CurrencyChangeController extends AbstractController
{
    #[Route("/", name: "currency_change")]
    public function index(): Response
    {
        return $this->render('secure/currency_change/index.html.twig', [
            'controller_name' => 'CurrencyChangeController',
        ]);
    }
}

src/Controller/Secure/CurrencyController.php
<?php

namespace App\Controller\Secure;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route("/currency")]
class CurrencyController extends AbstractController
{
    #[Route("/", name: "currency")]
    public function index(): Response
    {
        return $this->render('secure/currency/index.html.twig', [
            'controller_name' => 'CurrencyController',
        ]);
    }
}

templates/secure/crud_customer/_delete_form.html.twig
<form method="post" action="{{ path('secure_crud_customer_delete', {'id': customer.id}) }}" onsubmit="return confirm('Está usted seguro que desea eliminar este elemento?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ customer.id) }}">
    <button style="width: 80px" class="btn btn-danger m-1">Eliminar</button>
</form>

templates/secure/crud_customer/_form_search.html.twig
{{ form_start(form, {'attr': {'id': 'customer_search'}}) }}
    <div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>

    <div class="row">
        <div class="col">
            {{ form_row(form.name) }}
        </div>       
        <div class="col-2">
            <div class="mb-3">
                <label class="form-label" for="customer_search">&nbsp;</label>
                <button class="btn btn-primary form-control">Buscar</button>
            </div>
        </div>
    </div>
{{ form_end(form) }}

templates/secure/crud_customer/abm_customer.html.twig
{% extends 'home/index.html.twig' %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    {{ parent() }}
    <div class="d-flex justify-content-between">
        <div class="col-6">
            <h1 class="mr-auto mb-0 title-table">
                {{ title }}
            </h1>
        </div>
        <div class="col-6 text-end">
            <a class="btn btn-success" href="{{ path('secure_crud_customer_new') }}">
                Nuevo cliente
                            
            </a>
        {# <a class="btn btn-success" href="{{ path('secure_crud_customer_new') }}">Importar</a> #}
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12">
            <div class="table-responsive">
                <table id="table_full_buttons" class="table table-striped table-sm nowrap" data-order="[[ 1, &quot;desc&quot; ],[ 2, &quot;asc&quot; ],[ 3, &quot;asc&quot; ]]">
                    <thead>
                        <tr>
                            <th data-type="num" class="text-center">
                                Id. &nbsp;
                            </th>
                            <th>
                                Nombres/R.Social &nbsp;
                            </th>
                            <th>
                                E-Mail &nbsp;
                            </th>
                            <th>
                                Província &nbsp;
                            </th>
                            <th>
                                Localidad/Ciudad &nbsp;
                            </th>
                            <th>
                                Dirección
                            </th>
                            <th class="text-center" data-orderable="false">
                                Tel. Celular &nbsp;
                            </th>
                            <th class="text-center">
                                Fecha alta &nbsp;
                            </th>
                            <th class="text-center" data-orderable="false">
                                Acciones &nbsp;
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for customer in customers %}
                            <tr>
                                <td data-type="num" class="text-center">
                                    {{ customer.id }}
                                </td>
                                <td>
                                    {{ customer.name }}
                                </td>
                                <td>
                                    <a href="mailto:{{ customer.email }}" target="_blank" title="Enviar correo a {{ customer.email }}">
                                        {{ customer.email }}
                                    </a>
                                </td>
                                <td>
                                    {{ customer.state.name }}
                                </td>
                                <td>
                                    {{ customer.city.name }}
                                </td>
                                <td>
                                    {{ customer.streetAddress ~' '~ customer.numberAddress ~' '~ customer.floorApartment }}
                                </td>
                                <td class="text-center">
                                    <a href="tel:+549{{customer.codeArea ~ customer.celphone}}">({{customer.codeArea}}) {{customer.celPhone}}</a>
                                </td>

                                <td data-order="{{ customer.registration_date|date('U') }}" class="text-center">
                                    {{ customer.registration_date|date("d/m/Y") }}
                                </td>
                                <td class="text-center">
                                    <a style="font-size:16px" class="text-warning m-2" href="{{ path('secure_crud_customer_edit', {'id': customer.id}) }}" title="Editar cliente">
                                        <i class="fas fa-user-edit"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row mt-5 mb-5">
        <div class="col-12 text-end">
            <a class="btn btn-secondary" href="{{ path('app_homepage') }}">
                Regresar
            </a>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
{% endblock %}

templates/secure/crud_customer/customer_form.html.twig
{% extends 'home/index.html.twig' %}

{% block title %}
	{{ title }}
{% endblock %}

{% block content %}
	{{parent()}}
	<div class="row">
		<div class="col-12">
			<h1 class="mr-auto mb-0 title-table">{{ title }}</h1>
		</div>
		<div class="row">
			<div class="col-12 mt-3">
				{{ form_start(form) }}
				{% if form_errors(form) %}
					<div class="alert alert-danger">
						{{ form_errors(form) }}
					</div>
				{% endif %}

				<div class="row my-2">
					<div class="col-12">
						<h5 class="mr-auto mb-0 title-table">Datos del cliente</h5>
					</div>
				</div>
				<div class="row my-2">
					<div class="col-md-3">
						{{ form_row(form.name) }}
					</div>
					<div class="col-md-3">
						{{ form_row(form.email) }}
					</div>
					<div class="col-md-3">
						{{ form_row(form.identity_number) }}
					</div>
					<div class="col-1">
						{{ form_row(form.code_area) }}
					</div>
					<div class="col-2">
						{{ form_row(form.cel_phone) }}
					</div>
				</div>

				<div class="row my-2">
					<div class="col-xs-12 col-md-3">
						{{ form_label (
							form.state,
							'Provincia *',
							{'label_attr': {'class': 'form-label','id':'label-state','data-state-id':customer.state ? customer.state.id:'0'}}
						)}}
						{{ form_widget (form.state) }}
						{{ form_errors (form.state)}}
					</div>


					<div class="col-xs-12 col-md-3">
						{{ form_label (
							form.city,
							'Localidad/Ciudad *',
							{'label_attr': {'class': 'form-label','id':'label-city','data-city-id':customer.city ? customer.city.id:'0'}}
						)}}
						{{ form_widget (form.city) }}
						{{ form_errors (form.city)}}
					</div>


					<div class="col-md-4">
						{{ form_row(form.street_address) }}
					</div>
					<div class="col-1">
						{{ form_row(form.number_address) }}
					</div>
					<div class="col-1">
						{{ form_row(form.floor_apartment) }}
					</div>


				</div>
				{% if form.vars.value.id %}
					<div class="row my-2">
						<div class="col-12">
							{{ form_row(form.reset_password) }}
						</div>
					</div>
				{% endif %}
				<hr>
				<div class="row my-2">
					<div class="col-12 text-end">
						<a class="btn btn-secondary" href="{{ path('secure_crud_customer_index') }}">Regresar</a>

						<button class="btn btn-success">Guardar</button>
					</div>
				</div>


				{{ form_end(form) }}

			</div>
		</div>
	</div>

{% endblock %}

templates/secure/crud_customer/edit.html.twig
{% extends 'home/index.html.twig' %}

{% block title %}Editar cliente{% endblock %}

{% block content %}
    <h1>Editar cliente</h1>
    {{ include('secure/crud_customer/_form.html.twig', {'button_label': 'Update'}) }}
{% endblock %}

templates/secure/crud_customer/new.html.twig
{% extends 'home/index.html.twig' %}

{% block title %}{{ title }}
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-12">
			<h1 class="mr-auto mb-0 title-table">{{ title }}</h1>
		</div>
		<div class="row">
			<div class="col-12 mt-3">
				{{ include('secure/crud_customer/_form.html.twig') }}
			</div>
		</div>
	</div>

{% endblock %}

templates/secure/crud_customer/show.html.twig
{% extends 'home/index.html.twig' %}

{% block title %}Cliente{% endblock %}

{% block content %}
    <h1>{{ customer.billingFirstName }} {{ customer.billingLastName }}</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Imagen</th>
            {% if customer.image %}
                <td><img class="img-fluid rounded " width="120px" alt="Imagen" src="{{ asset(customer.image) }}"/></td>
            {% else %}
                <td><img class="img-fluid rounded " width="120px" alt="Imagen" src="{{ asset('uploads/images/default.jpg') }}"/></td>
            {% endif %} 
        </tr>
        <tr>
            <th>Identificación</th>
            <td>{{ customer.identification }}</td>
        </tr>
        <tr>
            <th>País</th>
            <td>{{ customer.billingCountry }}</td>
        </tr>
        <tr>
            <th>Provincia</th>
            <td>{{ customer.billingState }}</td>
        </tr>
        <tr>
            <th>Municipio</th>
            <td>{{ customer.billingCity }}</td>
        </tr>
        <tr>
            <th>Dirección</th>
            <td>{{ customer.billingAddress }}</td>
        </tr>
        <tr>
            <th>Código Postal</th>
            <td>{{ customer.billingPostcode }}</td>
        </tr>
        <tr>
            <th>Teléfono</th>
            <td>{{ customer.billingPhone }}</td>
        </tr>
        {# <tr>
            <th>Teléfono celulr</th>
            <td>{{ customer.cellPhone }}</td>
        </tr> #}
        <tr>
            <th>Oficina de retiro</th>
            <td>{{ customer.billingCompanyName }}</td>
        </tr>
        <tr>
            <th>Correo eletrónico</th>
            <td>{{ customer.billingEmail }}</td>
        </tr>
        </tbody>
    </table>
    <div class="d-inline-flex">
        <a style="width: 80px" class="btn btn-secondary m-1" href="{{ path('secure_crud_customer_index') }}">Regresar</a>
        <a style="width: 80px" class="btn btn-warning m-1" href="{{ path('secure_crud_customer_edit', {'id': customer.id}) }}">Editar</a>
        {{ include('secure/crud_customer/_delete_form.html.twig') }}
    </div>
{% endblock %}